"""Agent-host setup helpers for Claude Code and Codex.

The research core is host-neutral: MCP servers, hooks, and the cockpit all
cooperate through the same SQLite state file. This module owns only the thin
project-local configuration layer that lets a user choose Claude Code, Codex,
or both during setup.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

HOST_CLAUDE = "claude"
HOST_CODEX = "codex"
HOST_BOTH = "both"
HOST_CHOICES = (HOST_CLAUDE, HOST_CODEX, HOST_BOTH)

_GENERATED_HEADER = "# Generated by claudescientist setup. Edit if your local setup differs.\n"

_MCP_SERVERS: tuple[tuple[str, str, list[str], dict[str, str]], ...] = (
    (
        "memory",
        "uv",
        ["run", "python", "-m", "memory_mcp.dev_server"],
        {"RESEARCH_AGENT_DEV": "1"},
    ),
    (
        "verify",
        "uv",
        ["run", "python", "-m", "verify_mcp.dev_server"],
        {"RESEARCH_AGENT_DEV": "1"},
    ),
    (
        "prove",
        "uv",
        ["run", "python", "-m", "prove_mcp.dev_server"],
        {"RESEARCH_AGENT_DEV": "1"},
    ),
    (
        "lean",
        "uv",
        ["run", "python", "scripts/lean_mcp_or_noop.py"],
        {"LEAN_PROJECT_PATH": ".research-agent/lean/claudescientist-proofs"},
    ),
    (
        "cockpit",
        "uv",
        ["run", "python", "-m", "cockpit.mcp_server"],
        {"RESEARCH_AGENT_DEV": "1"},
    ),
    ("arxiv", "uv", ["tool", "run", "arxiv-mcp-server==0.5.0"], {}),
    ("openalex", "npx", ["-y", "openalex-research-mcp@0.5.0"], {}),
)

_CODEX_DISABLED_MCP_SERVERS = {"arxiv", "lean", "openalex"}

_HOOKS: tuple[tuple[str, str | None, str, str], ...] = (
    (
        "PreToolUse",
        "Read|Write|Edit|Bash|apply_patch|exec_command",
        "leakage_guard",
        "Checking held-out and provenance guard",
    ),
    (
        "PreToolUse",
        "Bash|exec_command",
        "destructive_bash_guard",
        "Checking destructive command guard",
    ),
    (
        "PostToolUse",
        "Bash|exec_command",
        "provenance_log",
        "Recording numeric provenance",
    ),
    (
        "UserPromptSubmit",
        None,
        "intervention_pump",
        "Loading cockpit interventions",
    ),
    ("Stop", None, "intervention_pump", "Draining cockpit interventions"),
    ("Stop", None, "stop_flush", "Recording turn summary"),
)


@dataclass(frozen=True)
class HostSetupResult:
    """Files changed while preparing an agent host."""

    written: tuple[Path, ...]
    checked: tuple[Path, ...] = ()


def normalize_agent_host(value: str | None) -> str:
    """Return a valid host value, defaulting to Claude Code."""

    candidate = (value or HOST_CLAUDE).strip().lower().replace("_", "-")
    aliases = {
        "claude-code": HOST_CLAUDE,
        "claudecode": HOST_CLAUDE,
        "claude": HOST_CLAUDE,
        "codex-cli": HOST_CODEX,
        "codex-desktop": HOST_CODEX,
        "codex": HOST_CODEX,
        "all": HOST_BOTH,
        "both": HOST_BOTH,
    }
    return aliases.get(candidate, HOST_CLAUDE)


def check_claude_support(repo_root: Path) -> HostSetupResult:
    """Check the checked-in Claude Code support files without mutating them."""

    paths = (
        repo_root / ".claude" / "settings.json",
        repo_root / ".claude" / "hooks",
        repo_root / ".claude" / "agents",
        repo_root / ".claude" / "skills",
    )
    return HostSetupResult(written=(), checked=paths)


def ensure_codex_support(repo_root: Path) -> HostSetupResult:
    """Create or refresh project-local Codex support files.

    Codex reads project configuration from ``.codex/config.toml``, custom
    subagents from ``.codex/agents/*.toml``, and repo-scoped skills from
    ``.agents/skills``. We derive the latter two from the existing Claude Code
    assets so the two hosts stay aligned.
    """

    written: list[Path] = []
    config_path = repo_root / ".codex" / "config.toml"
    if _write_if_changed(config_path, build_codex_config(repo_root)):
        written.append(config_path)

    written.extend(_sync_codex_agents(repo_root))
    written.extend(_sync_codex_skills(repo_root))
    written.extend(_sync_plugin_skills(repo_root))
    return HostSetupResult(written=tuple(written))


def build_codex_config(repo_root: Path) -> str:
    """Return the project-scoped Codex config TOML."""

    cwd = str(repo_root.resolve())
    blocks = [
        _GENERATED_HEADER.rstrip(),
        "",
        "# Project-local Codex adapter for ClaudeScientist.",
        "# Trust the project before relying on this layer; untrusted projects",
        "# ignore .codex config, hooks, and agents.",
        "",
        "[features]",
        "hooks = true",
        "multi_agent = true",
        "",
        "[agents]",
        "max_depth = 1",
        "",
    ]
    for name, command, args, env in _MCP_SERVERS:
        blocks.extend(
            _mcp_server_block(
                name,
                command,
                args,
                env,
                cwd,
                enabled=name not in _CODEX_DISABLED_MCP_SERVERS,
            )
        )
    for event, matcher, hook_name, status in _HOOKS:
        blocks.extend(_hook_block(event, matcher, hook_name, status))
    return "\n".join(blocks).rstrip() + "\n"


def _mcp_server_block(
    name: str,
    command: str,
    args: list[str],
    env: dict[str, str],
    cwd: str,
    *,
    enabled: bool,
) -> list[str]:
    lines: list[str] = []
    if name == "lean":
        lines.append("# Lean is optional. Enable this after completing docs/setup-lean.md.")
    elif name in {"arxiv", "openalex"}:
        lines.append("# External literature search is optional; enable only when needed.")
    lines.extend(
        [
            f"[mcp_servers.{name}]",
            f"enabled = {_toml_bool(enabled)}",
            f"command = {_toml_string(command)}",
            f"args = {_toml_string_list(args)}",
            f"cwd = {_toml_string(cwd)}",
            "startup_timeout_sec = 30.0",
        ]
    )
    if env:
        lines.append(f"env = {_toml_inline_table(env)}")
    lines.append("")
    return lines


def _hook_block(
    event: str,
    matcher: str | None,
    hook_name: str,
    status: str,
) -> list[str]:
    lines = [f"[[hooks.{event}]]"]
    if matcher is not None:
        lines.append(f"matcher = {_toml_string(matcher)}")
    lines.extend(
        [
            "",
            f"[[hooks.{event}.hooks]]",
            'type = "command"',
            "command = "
            + _toml_string(
                "uv run --no-sync python -m claudescientist.codex_hooks "
                f"{hook_name} --event {event}"
            ),
            "timeout = 5",
            f"statusMessage = {_toml_string(status)}",
            "",
        ]
    )
    return lines


def _sync_codex_agents(repo_root: Path) -> tuple[Path, ...]:
    source_dir = repo_root / ".claude" / "agents"
    target_dir = repo_root / ".codex" / "agents"
    if not source_dir.is_dir():
        return ()

    written: list[Path] = []
    for source in sorted(source_dir.glob("*.md")):
        parsed = _parse_claude_agent(source)
        if parsed is None:
            continue
        name, description, body, tool_hint = parsed
        target = target_dir / f"{source.stem}.toml"
        text = _codex_agent_toml(name, description, body, tool_hint)
        if _write_if_changed(target, text):
            written.append(target)
    return tuple(written)


def _parse_claude_agent(source: Path) -> tuple[str, str, str, str] | None:
    text = source.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None
    metadata: dict[str, str] = {}
    for line in parts[1].splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        metadata[key.strip()] = value.strip()
    name = metadata.get("name") or source.stem
    description = metadata.get("description") or f"ClaudeScientist {name} agent."
    tool_hint = metadata.get("tools", "")
    return name, description, parts[2].strip() + "\n", tool_hint


def _codex_agent_toml(
    name: str,
    description: str,
    body: str,
    tool_hint: str,
) -> str:
    instructions = body
    if tool_hint:
        instructions += (
            "\nCodex adapter note: the original Claude Code agent requested "
            f"these tools: {tool_hint}. Use the matching Codex tools and MCP "
            "servers when available; otherwise report the missing capability.\n"
        )
    return (
        _GENERATED_HEADER
        + f"name = {_toml_string(name)}\n"
        + f"description = {_toml_string(description)}\n"
        + "developer_instructions = "
        + _toml_multiline_literal(instructions)
        + "\n"
    )


def _sync_codex_skills(repo_root: Path) -> tuple[Path, ...]:
    source_dir = repo_root / ".claude" / "skills"
    target_dir = repo_root / ".agents" / "skills"
    if not source_dir.is_dir():
        return ()

    written: list[Path] = []
    for source in sorted(source_dir.rglob("*")):
        if not source.is_file():
            continue
        relative = source.relative_to(source_dir)
        target = target_dir / relative
        if not target.exists() or source.read_bytes() != target.read_bytes():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
            written.append(target)
    return tuple(written)


def _sync_plugin_skills(repo_root: Path) -> tuple[Path, ...]:
    """Refresh the standard plugin ``skills/`` publishing surface."""
    source_dir = repo_root / ".claude" / "skills"
    target_dir = repo_root / "skills"
    if not source_dir.is_dir():
        return ()

    written: list[Path] = []
    for source in sorted(source_dir.rglob("*")):
        if not source.is_file():
            continue
        target = target_dir / source.relative_to(source_dir)
        if not target.exists() or source.read_bytes() != target.read_bytes():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
            written.append(target)
    return tuple(written)


def _write_if_changed(path: Path, text: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def _toml_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\b", "\\b")
        .replace("\t", "\\t")
        .replace("\n", "\\n")
        .replace("\f", "\\f")
        .replace("\r", "\\r")
    )
    return f'"{escaped}"'


def _toml_string_list(values: list[str]) -> str:
    return "[" + ", ".join(_toml_string(value) for value in values) + "]"


def _toml_inline_table(values: dict[str, str]) -> str:
    parts = [f"{key} = {_toml_string(value)}" for key, value in sorted(values.items())]
    return "{ " + ", ".join(parts) + " }"


def _toml_bool(value: bool) -> str:
    return "true" if value else "false"


def _toml_multiline_literal(value: str) -> str:
    if "'''" not in value:
        return "'''\n" + value.rstrip() + "\n'''"
    return _toml_string(value)


__all__ = [
    "HOST_BOTH",
    "HOST_CLAUDE",
    "HOST_CODEX",
    "HOST_CHOICES",
    "HostSetupResult",
    "build_codex_config",
    "check_claude_support",
    "ensure_codex_support",
    "normalize_agent_host",
]
